Issue#12
Taki1010y/namecard pull request #21
Opened 2022-04-14 17:36 UTC by Taki1010y

refts #12

2022-04-16 05:38 UTC, sueno0311 commented on config/routes.rb
> +  devise_scope :cimpanles do
ここは単数系が正しいですね！

2022-04-16 05:44 UTC, Taki1010y commented on config/routes.rb
> +  devise_scope :cimpanles do
こちらの単語ですが、複数形なら「companies」単数形なら「company」に直したいのですが、その場合は手打ちになりますでしょうか？

2022-04-16 05:46 UTC, sueno0311 commented on config/routes.rb
> +  devise_scope :cimpanles do
そうですね！手で直接修正いただくのが早いかなと思います！
コントローラー、ビューのディレクトリも修正する必要があるので注意してください！

2022-04-16 05:49 UTC, Taki1010y commented on config/routes.rb
> +  devise_scope :cimpanles do
ありがとうございます！！！！

2022-04-24 22:38 UTC, sueno0311 requested changes

2022-04-24 22:38 UTC, sueno0311 commented on app/controllers/companies/mailer.rb
> +class Users::Mailer < Devise::Mailer
こちらはCompanies::Mailerになるかなと思われます！

2022-04-24 22:38 UTC, sueno0311 commented on app/assets/javascripts/detail.coffee
> +# Place all the behaviors and hooks related to the matching controller here.
coffee_scriptは使用しないので不要ファイルは削除しましょう！

2022-04-24 22:38 UTC, sueno0311 commented on app/assets/javascripts/register.coffee
> +# Place all the behaviors and hooks related to the matching controller here.
こちらも同様です。

2022-04-24 22:38 UTC, sueno0311 commented on app/models/user.rb
> +         :recoverable, :rememberable, :validatable, :confirmable #←confirmableを追加
#←confirmableを追加
こういったコメントは教材用にあるため削除しておいた方がよさそうです。

2022-04-24 22:38 UTC, sueno0311 commented on app/views/companies/registrations/new.html.erb
> +            <span class="ml-1 samazon-require-input-label">
samazonという単語が使われている場所が残っているので、必要であれば直しましょう

2022-04-24 22:38 UTC, sueno0311 commented on app/models/company.rb
> +         :recoverable, :rememberable, :validatable, :confirmable
バリデーションがかかっていないので、追加しておいた方がよさそうです。

2022-04-24 22:38 UTC, sueno0311 commented on app/models/user.rb
>  end
バリデーションがかかっていないので、追加しておいた方がよさそうです。

2022-04-24 22:38 UTC, sueno0311 commented on app/controllers/companies/registrations_controller.rb
> +    super(resource)
sign_up後の導線がルートパスになっているので適宜修正してください

2022-04-24 22:38 UTC, sueno0311 commented on app/controllers/companies/confirmations_controller.rb
> +  # def after_confirmation_path_for(resource_name, resource)
メールアドレス確認後の導線も適宜変更ください。（おそらく次のissuesで修正？）

2022-05-06 04:35 UTC, sueno0311 commented
sign_up後の導線は次のissueで実装って感じですかね？

もしそうであればOKだと思いますので、mainへマージしましょう！

2022-05-06 04:36 UTC, sueno0311 approved these changes

2022-05-06 04:40 UTC, merged